### ISSUE TITLE
DEFAULT-ADMIN-ROLE is not granted to CONTRACT-ADMIN

### ISSUE THREAD

**Issue by Saddam-tech** [JoinOrigami/crane#35]
I tried deploying the set of contracts to local anvil network and run the local-deploy script with all the necessary arguments, after deployment I tried testing the OrigamiMembershipToken.sol contract to mint tokens, but my admin does not have MINTER-ROLE, how do I grant all the permissions to my contract admin? Is it not supposed to grant all the permissions to the contract admin whose wallet address was specified while running the local-deploy script?

**Comment by mrmemes-eth** [comment]
The address passed in as the first argument to the `OrigamiMembershipToken::initialize` function is assigned the `MINTER_ROLE` role:

https://github.com/chaindrop-raas/crane/blob/5e1386ccb00297c6b60568e3f670ebebb26a90fc/src/OrigamiMembershipToken.sol#L84-L88

Looking through the `LocalDeploy` script, it looks like `configureTokens` function does call initialize with the correct address:

https://github.com/chaindrop-raas/crane/blob/5e1386ccb00297c6b60568e3f670ebebb26a90fc/script/LocalDeploy.s.sol#L215

Whatever's passed as the first argument for the `LocalDeploy` script invocation should receive `MINTER_ROLE` on `OrigamiMembershipToken`:

https://github.com/chaindrop-raas/crane/blob/5e1386ccb00297c6b60568e3f670ebebb26a90fc/script/LocalDeploy.s.sol#L48

If you're using the `bin/jib` shell script, whatever is passed as argument one to `./bin/jib local-deploy` looks like it's passed in in the correct spot for getting all the admin roles.

https://github.com/chaindrop-raas/crane/blob/5e1386ccb00297c6b60568e3f670ebebb26a90fc/bin/jib#L481-L497

For a local anvil node, you can test to see if the role is present like this:

```shell
cast call $MEMBERSHIP_TOKEN_ADDRESS "hasRole(bytes32,address)" \
  0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6 \
  $ADMIN_ADDRESS
```

... `0x00..00` is false, `0x00..01` is true. Just remember to fill in the correct addresses in that command.

**Comment by Saddam-tech** [comment]
Sorry for a late response, keep getting 0x000..00 from the hasRole function, could there be any misunderstanding while trying to configure the governor to use the facets? I am using these contract addresses to configure the governor: `./bin/jib cg -p [PRIVATE KEY OF CONTRACT ADMIN] [ADDRESS GovernorDiamondInit] [ADDRESS GovernorCoreFacet] [ADDRESS OF THE GovernorTimelockControlFacet] [PATH TO JSON CONFIG]` => `./bin/jib cg -p 0xeaa861a9a01391ed3d587d8a5a84ca56ee277629a8b02c22093a419bf240e65d 0xb581c9264f59bf0289fa76d61b2d0746dce3c30d 0x6d925938edb8a16b3035a4cf34faa090f490202a 0x40bde52e6b80ae11f34c58c14e1e7fe1f9c834c4 ./configs/local-config.json` . I keep getting `EvmError: Revert`. What could be the issue? Does it have a relation with my admin not being able to receive any role?

**Comment by mrmemes-eth** [comment]
Hmmm. There's a lot that can go sideways with the configuration for a governor (since it's complicated and error-prone). I'd definitely try to minimize the problem space and see if you can get the membership token deployed and verify that the configuration there is correct before trying to tackle the governor deploy and config.

Generally speaking, something that may prove helpful is calling the underlying `forge` and/or `cast` commands directly and calling them with the `-vvvvv` modifier so you get every possible level of detail.

**Comment by Saddam-tech** [comment]
Thanks for the reply! I think I figured out the problem, I was trying to call the implementation contract address previously, now that I call the membership token proxy contract it works! Have a great day!

**Comment by mrmemes-eth** [comment]
> I was trying to call the implementation contract address previously

I've done this more times than I care to admit 🤦‍♂️ I'm glad you were able to figure it out, good job debugging!
